version: '3'

volumes:
  mysqldb:

services:
  mysqldb:
    image: diary_app/mysql:latest
    container_name: mysqldb
    hostname: mysqldb
    restart: unless-stopped
    ports:
      - 3308:3306
    environment:
      - MYSQLDB_USER=user
      - MYSQLDB_PASSWORD=password
      - MYSQLDB_DATABASE=diary_app
    volumes:
      - mysqldb:/diary_app/diaryappvolume
#      -
#  d25228e41f99db945d45c0a8c657d6baf8697f21d066b8f76b14be3dba690d69